# Generated by Django 5.2.6 on 2025-09-11 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('SE', 'Software Engineer'), ('SSE', 'Senior Software Engineer'), ('LEAD', 'Tech Lead'), ('ARCH', 'Architect')], max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('technology', models.CharField(choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('JAVASCRIPT', 'JavaScript'), ('NODEJS', 'Node.js'), ('REACT', 'React')], max_length=50)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], max_length=50)),
                ('purpose', models.CharField(choices=[('NEW_PROJECT', 'New Project'), ('REPLACEMENT', 'Replacement'), ('BACKFILL', 'Backfill')], max_length=50)),
                ('project_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External/Client')], max_length=50)),
                ('total_experience', models.CharField(choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-7', '5-7 Years'), ('7+', '7+ Years')], max_length=10)),
                ('relevant_experience', models.CharField(choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-7', '5-7 Years'), ('7+', '7+ Years')], max_length=10)),
                ('tenure', models.CharField(choices=[('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year'), ('PERMANENT', 'Permanent')], max_length=20)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('number_of_openings', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('director_of_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doo_jobs', to=settings.AUTH_USER_MODEL)),
                ('first_round_interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_round_interviews', to=settings.AUTH_USER_MODEL)),
                ('floor_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_jobs', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_jobs', to=settings.AUTH_USER_MODEL)),
                ('second_round_interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_round_interviews', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(help_text='Select at least 3 skills.', to='jobs.skill')),
            ],
        ),
    ]
