# Generated by Django 5.2.6 on 2025-09-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr.')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('total_experience_months', models.PositiveIntegerField(help_text='Total experience in months.')),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('current_position', models.CharField(max_length=255)),
                ('notice_period_days', models.PositiveIntegerField(help_text='Notice period in days.')),
                ('highest_qualification', models.CharField(choices=[('HIGH_SCHOOL', 'High School'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('PHD', 'PhD')], max_length=50)),
                ('resume', models.FileField(blank=True, help_text='Attach resume file.', null=True, upload_to='resumes/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('is_whatsapp_number', models.BooleanField(default=False, verbose_name='Registered with WhatsApp')),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('technology', models.CharField(choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('JAVASCRIPT', 'JavaScript'), ('NODEJS', 'Node.js'), ('REACT', 'React'), ('DOT_NET', '.NET'), ('DEVOPS', 'DevOps')], max_length=50)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='House No/Flat No')),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('DL', 'Delhi'), ('MH', 'Maharashtra'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('UP', 'Uttar Pradesh')], max_length=50)),
                ('city', models.CharField(choices=[('DEL', 'Delhi'), ('MUM', 'Mumbai'), ('BLR', 'Bangalore'), ('CHN', 'Chennai'), ('LKO', 'Lucknow')], max_length=50)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_skills', models.ManyToManyField(blank=True, related_name='skilled_applicants', to='jobs.skill')),
            ],
        ),
    ]
